//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Invest_Site_3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Daily
    {
        public System.DateTime Date { get; set; }
        public string Tiker { get; set; }
        public int Position { get; set; }
        public float Price_Close { get; set; }
        public float Market_Value { get; set; }
        public float PL_Cum { get; set; }
        public int ID_Record { get; set; }
    }
}
